// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

import type { name } from './custom-types'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	WELCOME: RequiredParams<'name'>
	/**
	 * V​i​s​i​t​ ​<​>​{​u​r​l​}​<​>​ ​t​o​ ​r​e​a​d​ ​t​h​e​ ​d​o​c​u​m​e​n​t​a​t​i​o​n
	 * @param {name} url
	 */
	VISIT_WEBSITE: RequiredParams<'url'>
}

export type TranslationFunctions = {
	/**
	 * Welcome to {name}
	 */
	WELCOME: (arg: { name: string }) => LocalizedString
	/**
	 * Visit <>{url}<> to read the documentation
	 */
	VISIT_WEBSITE: (arg: { url: name }) => LocalizedString
}

export type Formatters = {}
